### ISSUE TITLE
Support multiple extra ips

### ISSUE THREAD

**Issue by johanhaleby** [jordic/k8s#4]
My current understanding is that you can only provide ONE extra IP to cloudsqlip. It would be great to allow for a list of extra ips instead.

**Comment by jordic** [comment]
I think you can append, more extra ips, just concating them with a coma (,):

188.166.20.115/32,188.166.21.115/32,188.166.22.115/32

The tool is super simple, and just builds a command around gcloud.

**Comment by johanhaleby** [comment]
Oh that's true. I just made made a small change, I'm going to provide it as a PR but feel free to disregard it since I'm not sure if it's a good idea (since you actually CAN already do this with finer precision (i.e. not only /32)).
